compile:
	g++ -O3 --std=c++2a SCCGC.cpp -o SCCGC

compile-opt:
	g++ -O3 --std=c++2a SCCGC.cpp -o SCCGC -Wall -Wextra -Wpedantic -pedantic-errors

compileD:
	g++ -O3 --std=c++2a SCCGD.cpp -o SCCGD

compile-opt-d:
	g++ -O3 --std=c++2a SCCGD.cpp -o SCCGD -Wall -Wextra -Wpedantic -pedantic-errors